app = "premier-league-bets"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://aqkuyzbznkybvluvvjzr.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxa3V5emJ6bmt5YnZsdXZ2anpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDg2NDEsImV4cCI6MjA2NDM4NDY0MX0.b-wENQ1HK3TMXF3lvde92ZPWNZBh3v-_gUUDZaQHxcQ"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  env = { NEXT_PUBLIC_SUPABASE_URL = "https://aqkuyzbznkybvluvvjzr.supabase.co", NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1Ni..." }

